### ISSUE TITLE
Connection troubles

### ISSUE THREAD

**Issue by Bratishkin1** [Numenorean/DurakOnlineBot#1]
Короче я запустил прогу на _дедике_, а она **не может** автоматом работать, не ломаясь. Проверил на 3-ех устройствах _ноуте_, _пк_ и _дедике_. В общем **везде** есть эта ошибка и прога ломается в течение +- 1 часа. Не надеюсь, что заметишь или вообще пофиксишь, но как говорится попытка не пытка.
**Ошибки**
 File "C:\Users\Администратор\Desktop\DurakOnlineBot-main — копия\main.py", line 74, in <module>
    start()
    └ <function start at 0x0000027103CFB4C0>

> File "C:\Users\Администратор\Desktop\DurakOnlineBot-main — копия\main.py", line 29, in start
    token = bot.register()
            │   └ <function DurakClient.register at 0x000002710E6281F0>
            └ <api.DurakClient object at 0x0000027103D4E7F0>

  File "C:\Users\Администратор\Desktop\DurakOnlineBot-main — копия\api.py", line 73, in register
    self.sock.sendall(
    │    │    └ <method 'sendall' of '_socket.socket' objects>
    │    └ <socket.socket fd=396, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('193.108.113.179', 62657), ...
    └ <api.DurakClient object at 0x0000027103D4E7F0>

ConnectionAbortedError: [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение
21:22:49.162An error has been caught in function 'start', process 'MainProcess' (4912), thread 'MainThread' (3620):
Traceback (most recent call last):

**Comment by dink3r1337** [comment]
Как получить ключ подписи запроса?

**Comment by zxcsom** [comment]
Пофиксил проблему. Скачать обновленный бот можете с моего [GitHub](https://github.com/zxcsom/DurakOnlineBot).

**Comment by mavlanovs421** [comment]
> Пофиксил проблему. Скачать обновленный бот можете с моего [GitHub](https://github.com/zxcsom/DurakOnlineBot).

t.me/Asdfdsafdasf пришли плиз, твой гит удален ((((

**Comment by mavlanovs421** [comment]
У меня такая вот ошибка https://i.imgur.com/JaQkThU.png
