### ISSUE TITLE
Проблема при включении Rucaptcha

### ISSUE THREAD

**Issue by ArtemCPU-cell** [Numenorean/DurakOnlineBot#12]
При включении работы с Rucaptcha в конфиге, при запросе катчи выбивает эту ошибку. 

ConnectionAbortedError: [WinError 10053] Программа на вашем хост-компьютере разорвала установленное подключение
02:54:54.336An error has been caught in function 'start', process 'MainProcess'(2924), thread 'MainThread' (6940):
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    start()
    └ <function start at 0x06087E38>

> File "main.py", line 29, in start
    token = bot.register()
            │   └ <function DurakClient.register at 0x0608F580>
            └ <api.DurakClient object at 0x002B9B80>

  File "Z:\WarThunder\DurakOnlineBot-main\api.py", line 73, in register
    self.sock.sendall(
    │    │    └ <method 'sendall' of '_socket.socket' objects>
    │    └ <socket.socket fd=164, family=AddressFamily.AF_INET, type=SocketKind.
SOCK_STREAM, proto=0, laddr=('192.168.0.14', 61629), rad...
    └ <api.DurakClient object at 0x002B9B80>

Токен проверялся много раз, он верен. Заранее спасибо

**Comment by ArtemCPU-cell** [comment]
Ошибка так же иногда бывает вот такой:
13:36:55.130An error has been caught in function 'start', process 'MainProcess'
(4048), thread 'MainThread' (2504):
Traceback (most recent call last):

  File "main.py", line 74, in <module>
    start()
    └ <function start at 0x061D6E38>

> File "main.py", line 29, in start
    token = bot.register()
            │   └ <function DurakClient.register at 0x061DE580>
            └ <api.DurakClient object at 0x01229B80>

  File "Z:\WarThunder\DurakOnlineBot-main\api.py", line 123, in register
    "id":captchaId,

UnboundLocalError: local variable 'captchaId' referenced before assignment
13:36:55.145An error has been caught in function 'start', process 'MainProcess'
(4048), thread 'MainThread' (2504):

**Comment by mvngr** [comment]
Сталкивался с подобным (больше знакомо второе сообщение)
Для меня было достаточным добавить одну строку в api.py:

```
        data1 = utils.unMarshal(self.sock.recv(4096).decode("utf-8", "ignore"))
        logger.debug(data1)
        data2 = utils.unMarshal(self.sock.recv(4096).decode("utf-8", "ignore"))
        logger.debug(data2)
        captcha = ""
        captchaId = "" # <---------------- вот эту
        url = data1[0].get("url") or data2[0].get("url")
```

**Comment by ArtemCPU-cell** [comment]
Решение не помогло. Ошибку с использование без объявления пропала, но другая ошибка так и осталась
